### ISSUE TITLE
satisfy function missing in source

### ISSUE THREAD

**Issue by DanielAsher** [ollie-williams/octopus#1]
hi,

the satisfy function seems to be missing. a challenge indeed, but intended?

**Comment by ollie-williams** [comment]
This got removed when I added the regular expression parser, which replaced all of the uses of it, and was more convenient to use. That said, there might be some occasion when `satisfy` is a better choice, so I just put it back in commit 3ce2a9b2ade4f58acedf828702cfeb6538f9217f.

**Comment by DanielAsher** [comment]
was an interesting test to implement. thanks for taking a look.
